### ISSUE TITLE
{"result":null,"error":{"message":"Check your login details","code":403}}

### ISSUE THREAD

**Issue by elixon01** [FOSSBilling/FOSSBilling#1072]
Hello, this new update shows the administrator with errors in the login to start section and when the data is entered and the section starts... It does NOT start the section and only shows errors in the login:

{"result":null,"error":{"message":"Check your login 
![Screenshot_20230405_095407](https://user-images.githubusercontent.com/97003979/230122849-478f01b4-22fe-4e1c-a7d7-276631288115.jpg)
![Screenshot_20230405_095358](https://user-images.githubusercontent.com/97003979/230122861-8a38d80e-5ee0-49f5-b31a-cb82f2c4918a.jpg)
details","code":403}}

my website is not hosted in the main directory and neither in a subdomain... if it is not a folder but this 4.1 update is modified for that so that it can work... but it still shows errors

**Comment by BelleNottelling** [comment]
Please try to access the page from a desktop browser and share any errors or warnings that are in the browser console

**Comment by elixon01** [comment]
It keeps giving the same error from the computer or from the cell phone,
it's the same and when it is possible to start the section, it throws an
error message in a blank image... that doesn't let me do anything

**Comment by BelleNottelling** [comment]
Hi there,

Please share any errors that are in the browser console when you try to access the page. Without more information, we will be unable to help you resolve this issue.

**Comment by elixon01** [comment]
Hello, I'll show you how the admin is reflected
in capture 1 it is the beginning of the section with errors.. in
capture2 it shows the user is entered and the section starts, it
throws that error verify the url as shown... in capture 3 I give it f5
update and the beginning of admin section with errors.. in capture4
and 5 it shows the closed section. in 4 it shows closed section I give
it f5 update and it shows that error

https://hostingamericano.com/my/api/guest/staff/login


2023-04-05 21:09 GMT-05:00, Belle Aerni ***@***.***>:

**Comment by BelleNottelling** [comment]
![image](https://user-images.githubusercontent.com/17304943/230466262-d2d26180-288c-4ad1-907d-4aad72758dcd.png)
It looks like there's likely an issue with the configured URL in your `config.php` file, or you need to edit your `.htaccess` file and configure the `RewriteBase` option. 

However, due to issues it causes & complexity introduces we will no longer be offering official support for installing FOSSBilling to a sub-folder.
You can find the related announcement on [our forum](https://forum.fossbilling.org/d/25-fossbilling-will-no-longer-provide-official-support-for-sub-folder-installations).

Joining [our discord](https://fossbilling.org/discord) would probably be the easiest way to get support with this change, however we can also provide support for it through the forum as well.
