### ISSUE TITLE
In order popup page selecting a product resets the custom language to English [Bug]

### ISSUE THREAD

**Issue by arminask** [FOSSBilling/FOSSBilling#1306]
### Describe the bug

When using a custom language, in the order popup box after selecting the product to order, the language switches from the custom selected one to default English (even though the translations are available for the custom language).

### How to reproduce

1. In client area click on "Order" button.
![image](https://github.com/FOSSBilling/FOSSBilling/assets/72100724/9503bfee-581f-4f1c-9ffb-249e801b321e)

2. Select a product from the list.
![image](https://github.com/FOSSBilling/FOSSBilling/assets/72100724/24b1037f-710c-442c-aec8-80213d813e2b)

3. Custom language switches over to default English.
![image](https://github.com/FOSSBilling/FOSSBilling/assets/72100724/c3609564-6525-4c51-813a-8fec770f2c0f)

### Expected behavior

The language should stay the same

### FOSSBilling version

0.4.3

### Device

Desktop

### Information

- Device: Desktop PC
- OS: Windows 10
- Browser: Brave

**Comment by BelleNottelling** [comment]
In my test instance, I am unable to replicate this (just selected the french language for testing):
![image](https://github.com/FOSSBilling/FOSSBilling/assets/17304943/8805a47e-313b-4ab5-8cb9-911c14cf863a)

Do you possibly have English set as your browser's preferred language? FOSSBilling will use the browser's `HTTP_ACCEPT_LANGUAGE` header to use the language that best matches what the browser sends as it's preferred language.


It specifically selects the language in this order:
Cookies (Set when you manually select the language) -> preferred language as sent by the header -> config file.
Because of the way the order module works (and it's terrible), it functions on a separate path and even under a new session so it might not be picking up the language cookie which means the next source it'll use is that `HTTP_ACCEPT_LANGUAGE` header.

**Comment by arminask** [comment]
> In my test instance, I am unable to replicate this (just selected the french language for testing): ![image](https://user-images.githubusercontent.com/17304943/244818989-8805a47e-313b-4ab5-8cb9-911c14cf863a.png)
> 
> Do you possibly have English set as your browser's preferred language? FOSSBilling will use the browser's `HTTP_ACCEPT_LANGUAGE` header to use the language that best matches what the browser sends as it's preferred language.
> 
> It specifically selects the language in this order: Cookies (Set when you manually select the language) -> preferred language as sent by the header -> config file. Because of the way the order module works (and it's terrible), it functions on a separate path and even under a new session so it might not be picking up the language cookie which means the next source it'll use is that `HTTP_ACCEPT_LANGUAGE` header.

You're right, I just tested this on an incognito page and it worked, that's not a bug.

**Comment by BelleNottelling** [comment]
> You're right, I just tested this on an incognito page and it worked, that's not a bug.

Hey, I'm glad that was the issue.
For what it's worth, long-term we do plan on rewriting the [cart](https://github.com/FOSSBilling/FOSSBilling/issues/556) which should also resolve that specific edge-case once performed.
