### ISSUE TITLE
[Bug] Downloadable Product file is not replaced with the new one.

### ISSUE THREAD

**Issue by sixxt** [FOSSBilling/FOSSBilling#1405]
### Describe the bug

Whenever i try and upload a new file for a downloadable product, the order config is not updated with the new file path/name.

### Hosting informations:
Apache Version: 2.4.57
MySQL Version: 10.6.12-MariaDB-cll-lve
PHP Version: 8.1

### How to reproduce

1. Go to Products & Services and create a new Downloadable product (upload a file as well)
2. Order it using a alt account, also download the file for testing.
3. Change the product file in the Product Config.
4. Try downloading the file from the client area.

### Expected behavior

The file path/name should've been updated with the newly uploaded file. Resulting in a successful download in the client area.

### Screenshots

![Image](https://i.imgur.com/K9fesSm.gif)

### FOSSBilling version

0.5.3 Latest

### Device

Desktop

**Comment by Anuril** [comment]
Ok so from what I've been able to see, it's not a "bug" per se. If you update the product, the order itself doesn't get updated, but if you update the order, it actually updates the file for the client.

![grafik](https://github.com/FOSSBilling/FOSSBilling/assets/1939311/953b87c2-c28b-4197-bff8-1345daa9db01)

So I guess the question is what's the intended behaviour and what's the requested feature. 

This way, it's set up so that a customer can buy _the version that's online when he purchases it_. 

I guess we could add a feature where you can configure "Keep file updated" and it get's replaced when you upload a file.

**Comment by BelleNottelling** [comment]
> Ok so from what I've been able to see, it's not a "bug" per se. If you update the product, the order itself doesn't get updated, but if you update the order, it actually updates the file for the client.

If you update the product, it is supposed to update **all orders** associated with it as well. The only situation where it wouldn't be expected to do so is if you uploaded a new file to the order.

I do not know why there is even the ability to upload a new file to an order, though.
If that was removed then rather than each order having it's own filename record in the DB, they could all just point to the product.
The only use-case I can imagine for uploading a file to the order is if you are doing one-off files for download and manually creating orders for clients.

**Comment by Anuril** [comment]
To be honest, there's a lot of services where you either purchase an update agreement, or you purchase f.ex "All updates for this major version" - or "Buy V4 of my super handy self-help book". I think removing this would be removing functionality. I'd keep it, but provide the option to configure the product so it updates all orders that contain it.
