### ISSUE TITLE
Configurable maximum age for activity data retention

### ISSUE THREAD

**Issue by John-S4** [FOSSBilling/FOSSBilling#1673]
FOSSBilling records all API calls as well as many actions that clients or staff members may perform as well as information that's logged every time cron is run (should be once every 5min).

Currently this information is stored indefinitely, which means that on a  busy installation those DB tables can easily become huge over time. 

The solution is to implement a configurable maximum age for this information to be kept, after which it will be dropped from the database. This will be set by default at 90 days with a provided user configuration option to make the retention time longer/shorter.

**Comment by gilesytheking** [comment]
I was thinking about this the other day and totally agree the logs are going to be massive. I currently go through the logs periodically and manually delete the older ones.

An another possible solution could be to write the data to a log file, much like error logs in WordPress. A new log file would be generated for each day. Log files could be view from within the dashboard, or exported and saved externally. This would reduce the burden on the DB.
 
The option to retain logs for 90 days could still be implemented and older logs automatically deleted freeing up space.

**Comment by BelleNottelling** [comment]
Honestly.. logging activity to a log file rather than to the database would be a significant downgrade.

Although it isn't leveraged effectively now, logging to the database allows us to implement easier sorting and filtering options in the dashboard for viewing the activity logs, which is actually really important and helpful while also improving the performance of the logging.

If we switched to logging activity to a text file, it would become a massive issue to try and implement any kind of sorting functionality to it. If we wanted to do some kind of file that's actually designed to be programmatically interacted with like a JSON file, there's then the issue where we would have to load the entire file and process it within FOSSBilling when displaying things to the dashboard and adding to it would once again require that the entire thing is loaded, updated, and then written to the disk.

The database engine does all of this for us. We can simply ask for a specific range of activity items, apply filters, etc and the database engine will do all of the heavy lifting for us while also optimizing these requests so that they perform great. These types of actions are specifically what databases are great at.

The actual load that the logging places on the database isn't all that significant either as most of the time it's only adding new entries to the table, it's really just a question of how large someone is okay with those tables growing to, hence the plan to implement a configurable maximum age.
