### ISSUE TITLE
Localhost install 

### ISSUE THREAD

**Issue by BursaYazilimCom** [FOSSBilling/FOSSBilling#1693]
I'm trying to set up localhost, why can't I do it.

php version and mysql version are correct but not working

**Comment by BelleNottelling** [comment]
We have a getting stated guide which describes the basics for many setups:
https://fossbilling.org/docs/getting-started

And a troubleshooting document which when followed correctly will resolve most issues people have:
https://fossbilling.org/docs/troubleshooting

If you want help outside of that, please give more information because all "why can't I do it" and "but not working" tells me is that you likely don't care about the time that myself or someone else has to give to help you.

Thanks

**Comment by BursaYazilimCom** [comment]
I'm sorry, I misspoke. I can install it.

https://prnt.sc/9jry8jbkyGlN

But when I click on any link 
https://prnt.sc/UFsar88jau9u
or 
when I want to enter the admin panel 

https://prnt.sc/dhRJVtvPkYmW

Trying to view Wampserver's homepage

**Comment by jaapmarcus** [comment]
We don't support any more install in sub folders

**Comment by BelleNottelling** [comment]
Thank you providing more information.
Jaap is correct, an installation under a sub-folder won't behave correctly, although that doesn't explain everything you are seeing.

It also looks like the WAMP server is still running some kind of default config from WAMP that's causing conflicts with FOSSBilling.

**Comment by BursaYazilimCom** [comment]
How does https://demo.fossbilling.org/admin work if subdomain does not support it

**Comment by BelleNottelling** [comment]
Sub-domains work fine, sub-folders do not.

**Comment by BelleNottelling** [comment]
Closing due to how long it's been since this was opened & it being a configuration error
