### ISSUE TITLE
[Feature Request] Migrate the Tide theme into Foss Billing Core

### ISSUE THREAD

**Issue by gilesytheking** [FOSSBilling/FOSSBilling#1930]
As the tide theme is based on Tabler, it would make sense to bring this into the core of Foss Billing inline with the default admin template. As already highlighted there are some compatibility issues with the Tide theme going into v 0.6.0. The original dev has not worked on the tide template in the last 5 months and it would be a shame for the template to be incompatible with future updates of foss billing.

We can all agree that the look and layout of the admin template is great, being very modern and easy to navigate. By using Tabler for both Client and admin templates, it would make it much easier to implement template features and utilize the built in tabler layouts, to change to look and feel of the site.

Tabler includes loads of awesome elements and layouts that would be very useful for hosting seller applications, such as;

13 layout options including RTL
Pricing Tables
Pricing Cards
Invoice templates

Possibly options could be added in the template settings, allowing website owners to select which layout style they want to use and apply customizations such as default colors, button styles etc, making the client side template more customizable. 

You may have already started doing something like this with the latest Huraga updates, then awesome.

**Comment by BelleNottelling** [comment]
I'm going to close this, Tide has since received updates and is to the best of my understanding fully compatible with the latest releases of FOSSBilling.

Additionally, none of the regular FOSSBilling contributors are truly front-end developers so I don't think we want to maintain two separate themes for it at the moment.

I personally have plans to expand Huraga and add in more customization over time, but it's an issue of finding time in-between other items that are of a higher importance.
