### ISSUE TITLE
[Bug] Renewal invoices duplicate line items giving incorrect Invoice totals

### ISSUE THREAD

**Issue by gilesytheking** [FOSSBilling/FOSSBilling#1969]
### Describe the bug

I have noticed that line items are being duplicated on renewal invoices / Manually issued invoices. This mean the invoice total is incorrect.

This has occurred on my live site, with a clients invoice. The Invoice was auto generated based on "Number of days to generate new invoice before order expiration" setting . 

I have had to manually adjust the invoice. I have also tested this on my staging site with the same results.

### How to reproduce

- create a new order with a recurring product.
- Mark first invoice as paid.
- Navigate to order, click "issue invoice" to generate new invoice for the next period.

### Expected behavior

Renewal / Next invoices should be calculated correctly for the next billing period.

### Screenshots

![image](https://github.com/FOSSBilling/FOSSBilling/assets/15634270/14176aaf-4367-4dd0-b36b-9a881e6816a5)

![image](https://github.com/FOSSBilling/FOSSBilling/assets/15634270/fb2ff55f-25a9-4974-b1af-237097fc0b85)

![image](https://github.com/FOSSBilling/FOSSBilling/assets/15634270/13196f94-0c8a-44d9-962a-bdf62a79b374)

![image](https://github.com/FOSSBilling/FOSSBilling/assets/15634270/f62f0176-fb0d-4347-b13e-02585a5b6d09)

### FOSSBilling version

0.6.2

### FOSSBilling instance ID

937f3585-788d-4528-abfe-acaf2ec45d07

### Device

Desktop

**Comment by BelleNottelling** [comment]
I've identified #1494 as the problematic change for this.
It will either be fixed or entirely reverted within the hour

**Comment by gilesytheking** [comment]
> I've identified #1494 as the problematic change for this. It will either be fixed or entirely reverted within the hour

Thanks for the quick response on this one. Does this mean however that individual invoices will now be generated for each service / order rather than them being combined into one (when renewal date / group ID is the same)?

**Comment by BelleNottelling** [comment]
> Thanks for the quick response on this one. Does this mean however that individual invoices will now be generated for each service / order rather than them being combined into one (when renewal date / group ID is the same)?

Yes, but not for the reason you're thinking.
That's always been the behavior of invoices all the way since BoxBilling and it's just not yet something we've had the opportunity to refine at all.

The pull request was supposed to resolve an issue (still from BoxBilling) where add-ons got separate invoices generated on renewal. This has also always been the behavior for all preview release of FOSSBilling except 0.6.0, 0.6.1, and 0.6.2 before the revert happened.

Obviously separate invoices being generated is a bit clunky, but it's much better than renewals generating with duplicated line-items. So for now we get to revert to the clunky behavior and can work to resolve that at a later date with a change that doesn't also break critical functionality.
