### ISSUE TITLE
[Bug] Order Page via ID/Link no longer working

### ISSUE THREAD

**Issue by epichosts** [FOSSBilling/FOSSBilling#1993]
### Describe the bug

When configuring a product, there is a tab named 'Links' where it shows URLs to the ID and link for the product, the link of course named by the 'Slug' field in the 'General settings' tab, however since a recent update these are no longer working. They simply show the order page with what looks to be an older theme, as the currency box at the top no longer shows etc.

### How to reproduce

1. Create a product with a slug
2. Go to the 'links' tab and try to go to any URL
3. You will see the issue described

### Expected behavior

It is expected that the product shows exactly the same as when a product is selected on a new order.

### Screenshots

![1](https://github.com/FOSSBilling/FOSSBilling/assets/25933763/05c72a80-6c7a-47cb-ad8d-31deac81eb3c)

### FOSSBilling version

0.6.4 (the latest stable release)

### FOSSBilling instance ID

75a2c780-8d64-4f7c-aa8b-aac3050909eb

### Device

Desktop

### Information

N/A

**Comment by BelleNottelling** [comment]
Well I don't like saying this, but I am struggling to identify why this no longer works.
Actually, I'm struggling even to understand how the BoxBilling developers originally intended for the entire ordering system to function. It's an awful mesh of 3 different modules together and they are all interconnected in ways that just seem completely senseless.

I suspect some minor change in #1612 introduced the broken behavior, but everything I've seen that seems like it may be the culprit turns out to be essentially nothing and trying to find the problem feels about as effective as breathing through a straw that's plugged on one end when I don't even know how to breathe.

I'll give everything another look to in a bit to see if I can notice anything new, but most likely there will be no hotfix for this and it (plus the embed functionality) will remain broken until those 3 modules are rebuilt from the ground up, meaning 0.7.0 at the earliest.

For your use-case specifically, you do have a mini workaround by providing a different link.
Rather than https://billing.example.com/order/7 you can do https://billing.example.com/order?product=7

**Comment by BelleNottelling** [comment]
@epichosts
@4yx was able to find the missing piece of the puzzle that I missed, so this is has now been fixed as of 0.6.5! 😄
