### ISSUE TITLE
Knowledgebase not displaying as in editor

### ISSUE THREAD

**Issue by adamh2021** [FOSSBilling/FOSSBilling#2007]
### Describe the bug

When inserting a table within an knowledgebase article, in the admin editor - upon saving no table is shown within the client view of that article.

### How to reproduce

Knowledgebase editor > Create a table > Enter some info (Table looks good in editor) > Navigate to the front end article, table seems to retain shape, no lines or shading. 

### Expected behavior

Mirror what is shown in the knowledgebase editor. 

### Screenshots

<img width="875" alt="knowledgebase1" src="https://github.com/FOSSBilling/FOSSBilling/assets/94173435/64c8fc07-dc77-44d9-a663-32a65e7df3a6">
<img width="861" alt="knowledgebase" src="https://github.com/FOSSBilling/FOSSBilling/assets/94173435/afc80974-8766-4cd3-8cdf-fb985f9587ba">

### FOSSBilling version

0.6.4

### Device

Desktop

**Comment by BelleNottelling** [comment]
This is happening because of how Boostrap handles tables. It doesn't automatically apply styling to them as you have to manually apply CSS classes to them. Since all of the content is written in Markdown, no classes are applied by default.

I have some code I wrote for my CMS that allows themes within it to define default classes for various elements when rendering markdown. I'll adapt that code for FOSSBiling and use it in our default theme to apply the correct formatting.

**Comment by adamh2021** [comment]
@BelleNottelling Thanks for taking a look at this. Must admit, this is a little new to me. Will this come out in an update long with other fixes / improvements?

**Comment by jaapmarcus** [comment]
It should have been released today...

**Comment by adamh2021** [comment]
@jaapmarcus 

Thank you - My install eventually picked the update up - improvements work well.
