### ISSUE TITLE
[Bug] Sending emails to gmail accounts

### ISSUE THREAD

**Issue by Suckitup11** [FOSSBilling/FOSSBilling#2045]
### Describe the bug

I have tried to send emails to a gmail account and nothing is being received.  Is this an issue that is with some 3rd party emails?

### How to reproduce

I have tried resending emails with nothing being received. I have sent emails to a personal email off my personal server and email is received.

### Expected behavior

would figure no matter what email provider this is being sent to it would send.  no it is not in the spam folder as well.

### FOSSBilling version

6.5

### Device

Desktop

**Comment by Suckitup11** [comment]
oh before i forget.  When creating a new client it does not send the email.  I had to log in as the client and click resend then run the cron for it to even send to my personal email off the server.

**Comment by BelleNottelling** [comment]
There's a lot of moving parts when it comes to email delivery, and essentially all of these things are completely outside of our control and are up to you to validate and resolve issues with.
There's DNS configuration, reputation for your domain and IP address, the contents of the email. and, and more.
https://sendgrid.com/en-us/blog/email-delivery-failure-causes

In the case of gmail specifically, they like to outright block IP addresses from sending to gmail accounts and when it does any email coming from that address will never even make it into the recipient's spam filter. You can try to get allowed or just use a 3rd party SMTP service of which there are many.
https://massmailer.io/blog/how-to-remove-your-ip-from-gmails-blacklist/

> then run the cron for it to even send to my personal email off the server.

Yup, you should update because in 0.6.6 we made a change to ensure that verification emails are sent instantly rather than being queued and sent via cron:
https://github.com/FOSSBilling/FOSSBilling/releases/tag/0.6.6
