### ISSUE TITLE
[Bug] An exception has been thrown during the rendering of a template ("Undefined constant "CURL_SSLVERSION_TLSv1_2"")

### ISSUE THREAD

**Issue by mcginnisi** [FOSSBilling/FOSSBilling#2087]
### Describe the bug

I am getting an error message when trying to access the admin area after updating. The frontend works, but accessing admin areas leads to this error.
<img width="1283" alt="Screen Shot 2024-01-18 at 10 05 04 PM" src="https://github.com/FOSSBilling/FOSSBilling/assets/103005527/b61b56cf-82cb-4257-83f9-adf22b6c9528">

### How to reproduce

1. Have old version.
2. Update to newest version.
3. Go to https://yourdomain.com/admin or any other admin page, it gives this error.

### Expected behavior

I expected to be able to access my admin area after the update to edit some styling.

### Screenshots

<img width="1283" alt="Screen Shot 2024-01-18 at 10 05 04 PM" src="https://github.com/FOSSBilling/FOSSBilling/assets/103005527/be6b9322-e20c-4f92-b8e7-1c4ba33cb4af">

### FOSSBilling version

0.6.8 ---> 0.6.9 Auto Update

### FOSSBilling instance ID

1302c39c-b6ae-493b-ac39-7e632d82fdc5 

### Device

Desktop, Smartphone

### Information

Device: Mac and Iphone
OS: MacOS and iOS
Browser: Edge on both

**Comment by BelleNottelling** [comment]
Your server is running a version of cURL that is at least 10 years old.
It needs to be at the oldest version 7.34.0 which added in the `CURL_SSLVERSION_TLSv1_2` constant.

The specifics will depend on your server installation, but you'll need to update the cURL package on your server and then update / rebuild the PHP extension for it

**Comment by mcginnisi** [comment]
Hello,

I have updated PHP and cURL and the error remains. Please advise.

I now can no longer access it through my terminal and I am safe mode
accessing it. This update broke my system and I may have to roll it back.
Please advise what info you need to aide me. Thank you so much!

Isaac

**Comment by jaapmarcus** [comment]
I don't know what server OS you are running but managing a server doesn't fall in Fossbilling scope...

**Comment by mcginnisi** [comment]
I understand that,

What I stated was that I had to roll back the update. I did not ask for
help with the server.

My request for assistance was regarding the update of cURL and PHP which
still didn’t work. I have rolled it back to the previous version and
everything works, but every time I update to the new FOSS and manually
rebuild cURL and PHP to the right version it still does not work. That was
my request, because I did what you suggested and it still didn’t work.

The information I provided was to support my claim that the new update is
breaking things.

Please let me know if there’s any more info I can provide for you to help
advise me as to potential next steps. I know it’s open source and I’m not
paying, so I don’t expect an immediate resolution. Just some help with
getting it handled.

Thank you!

**Comment by BelleNottelling** [comment]
> The information I provided was to support my claim that the new update is breaking things.

There honestly isn't any bug with the new release. Anything since version 0.6.0 will run into this error if the cURL version isn't sufficient. Collectively those releases have close to 1500 downloads (some of these are upgrades, some fresh installs).

Of all of those downloads, only 3 people have reported this error including yourself and the other two people were able to resolve it by updating cURL and the cURL PHP extension. There is no bug on our end, just a configuration issue on your server. 

You haven't specified what your server is so I am going to assume that it's a CentOS server running CWP in which case I have a few suggestions for you:

1. I'd highly encourage you to start looking into upgrade paths for your OS as CentOS is discontinued. If you have anything other than CentOS 7, you're already outside of the provided [maintenance update time-frame](https://en.wikipedia.org/wiki/CentOS). (This includes CentOS 8 which was dropped 2 years ago and is **still** listed as a supported OS on the CWP site when it really shouldn't be used).
2. Verify that you actually rebuilt the correct version of PHP. If you have 3 or 4 different versions on your server and only updated one, the rest will still be out of date and that may be what your FOSSBilling installation is running on.
3. CWP has some documentation on how to update cURL to a later version because they know this is likely to be an issue. These steps are [here on their wiki](https://wiki.centos-webpanel.com/update-curl-to-latest-version-in-centos). Their guide as written should update you to cURL version `7.88.0` which still a year old, it should be more than recent enough to function correctly with modern software.
4. You could try asking Mike on our forum how he was able to resolve the issue for himself. The original post can be [found here](https://forum.fossbilling.org/d/118-error-after-newest-update/4). The forum allows you to sign in via GitHub, so you don't need to create a new account for it.

Outside of that, I'm not really sure what to tell you.
Our GitHub issues aren't really supposed to be used as a forum / tech support so if you can hop onto the [forum](https://forum.fossbilling.org/) or our [Discord](https://discord.com/invite/bVjMZSgtbY) we can have a bit more of a back-and-forth conversation trying to identify where you're having issues, but as-is this bug report isn't a bug and is non-actionable for us.

If you are going to join one so we can help easier, I personally would suggest using the Discord over the forum. Both work, but 99% of the time I am the only person responding on the forum and I only periodically check it unlike the Discord server which I look at regularly since I have Discord on my phone.

**Comment by BelleNottelling** [comment]
I'm going to close this as it's been a few weeks and we've already provided how to resolve the problem.
