### ISSUE TITLE
Separate the installer project from the main repository

### ISSUE THREAD

**Issue by evrifaessa** [FOSSBilling/FOSSBilling#214]
It will get complicated. I'm planning to make a complete rewrite and it should better have its own dedicated repo.

**Comment by evrifaessa** [comment]
https://github.com/FOSSBilling/installer

**Comment by John-S4** [comment]
Sorry, maybe I'm missing the point, but just want to clarify...

This is just to work on changes to the installer and then you will fold those changes back into the core repo, is that right?

If that is the case, then that's fine, but otherwise I really don't think it should be separated out, feels like adding complexity.

**Comment by jaapmarcus** [comment]
If it will get merged we should work in a branch not a new repo it doesn’t make sense

**Comment by John-S4** [comment]
> If it will get merged we should work in a branch not a new repo it doesn’t make sense

Also true. 

If it won't get merged then I think it's a mistake to separate it out from core - FOSSB is always going to ship including the installer.
