### ISSUE TITLE
[Bug] Checkout accordion contains links to privacy policy

### ISSUE THREAD

**Issue by ApioxFR** [FOSSBilling/FOSSBilling#2507]
### Describe the bug

![image](https://github.com/user-attachments/assets/a1d23cee-52a3-4f84-aeb2-a1b381766323)

Everything is wrapped with a link redirecting to the privacy policy, this is quite not user friendly...

### How to reproduce

go to product link and click on the accordion items before completing the current open accordion.

### Expected behavior

no links redirecting to policies, unless it's explicitly written on the link

### FOSSBilling version

0.6.22

### FOSSBilling instance ID

9167f921-1597-4a86-9f3e-9fcd7c2b21aa

### Device

Desktop

### Information

Chrome

**Comment by ApioxFR** [comment]
I deployed a local env to test this out, and this bug is produced by having an active form (from the form builder, with default settings)

**Comment by ApioxFR** [comment]
Changing the settings for huraga:

signup and checkout, for the TOS & PP from explicit agreement to implicit agreement fixes the issue.

**Comment by ApioxFR** [comment]
@BelleNottelling You got the same issue going on on your order page:
![image](https://github.com/user-attachments/assets/4c7fe9ef-f4d8-4555-b143-b02af18ac402)

**Comment by BelleNottelling** [comment]
That site was not running a preview build of FOSSBilling.
I updated it to the current preview build just now and I can confirm as I expected that the issue is gone.

If you want to run a preview build, you can edit your `config.php` file and change `update_branch` from `release` to `preview` and then use the updater to swap. The same thing works in reverse. (though the preview build has some oddities of it's own still, as it is a preview release)

Otherwise, I expect I'll have a new update out before the end of the year and you are more than welcome to wait for that to be out as well.
