### ISSUE TITLE
[Feature Request] Proxmox module

### ISSUE THREAD

**Issue by 0x6b-dev** [FOSSBilling/FOSSBilling#27]
https://github.com/boxbilling/boxbilling/issues/1313

**Comment by notbasetwo** [comment]
Will echo previous comments about this module. Proxmox is not built to be used as a "hosting" panel and as such is not a simple module to implement.

Parts of this module will require service management to be handled directly within FOSSBilling, for example - IP Address management and monitoring of bandwidth usage for service suspension.

In addition, most of the features you will need (stop/start/console/etc.) will realistically need to be provided from within BoxBilling's user interface - rather than from a link to Proxmox itself.

This is by no means impossible - but something that I think would exceed the scope of the project for the time being.

**Comment by John-S4** [comment]
Completely agree with @notbasetwo

It might be an interesting integration but it's not something that is quick or easy to implement and not something that fits with the basic things that FOSSBilling is designed to do. At some point down the road possibly but it's not just an add on module like actual hosting control panels would be.

**Comment by evrifaessa** [comment]
I'd love to have Proxmox integrated, but it wouldn't be really easy to implement given the extensibility of the current codebase and the absolute need for a more complex interface than regular hosting solutions.

**Comment by notbasetwo** [comment]
> I'd love to have Proxmox integrated, but it wouldn't be really easy to implement given the extensibility of the current codebase and the absolute need for a more complex interface than regular hosting solutions.

It is not just the interface, a competent module would require potentially work beyond just interacting with the proxmox API (especially in the case of say DHCP setup).

Waaaay beyond the scope of the project.

**Comment by mmm8955405** [comment]
If it cannot be integrated with proxmox or other virtualization. So what's the point of this system?

**Comment by jaapmarcus** [comment]
There are many other systems that do work. How ever feel free to submit a PR if you want to have this new feature faster ...

**Comment by mmm8955405** [comment]
> a competent module would require potentially work beyond just interacting with the proxmox API (especially in the case of say DHCP setup).

What kind of virtualization system does this system support? If nothing is supported, it is an empty box. Why should I use a PHP empty box?

**Comment by mmm8955405** [comment]
> There are many other systems that do work. How ever feel free to submit a PR if you want to have this new feature faster ...

Thank you. I just hope to have this module. If not, I can only look for other systems

**Comment by notbasetwo** [comment]
> > a competent module would require potentially work beyond just interacting with the proxmox API (especially in the case of say DHCP setup).
> 
> 
> 
> What kind of virtualization system does this system support? If nothing is supported, it is an empty box. Why should I use a PHP empty box?

Plenty of modules are supported, SolusVM being a big one.

Proxmox is **not** a hosting control panel and would require significant additional work to make it work in that way. There are proprietary (largely due to the effort required) modules for Proxmox in other panels and ProxCP which is available standalone.

It is definitely something we would love to do, but there are bigger fish to fry. It requires a lot more thought that just a few API calls. If you really want the feature though, as said - PRs welcome.

**Comment by 4yx** [comment]
> What's the point of this system?

Quoting: 
> FOSSBilling is a free open source, billing and client management solution.

That is the point of this system.

Support for systems can come from the community contributing them. The team's current objectives can be seen in the Roadmap: https://github.com/orgs/FOSSBilling/projects/2/views/8

As you may be able to see there, the Proxmox module is set in v.1.1.0. Given the difficulty of implementing this, as mentioned multiple times before by team members, and as directly stated above me, there are more important tasks that need attention before that.
If you'd like it sooner and can contribute, feel free to do so. Otherwise, you'll either have to wait (with no specific time or promises this will be implemented), or search for another system like you mentioned.

**Comment by evrifaessa** [comment]
I might work on this. At least with the basic features working.

**Comment by tobsowo** [comment]
Found something similar done on ISPConfig
https://git.ispconfig.org/EXT/proxmox

**Comment by BelleNottelling** [comment]
There is now a Proxmox module under our repo, it's been ported over from a module someone created for BoxBilling about 6 years ago. Basic functionality does work on it, but it needs more work for sure.
The repo:

**Comment by mmm8955405** [comment]
Any progress? expect

**Comment by 4yx** [comment]
> Any progress?

All progress can be seen on the Proxmox repository: https://github.com/FOSSBilling/Proxmox

**Comment by evrifaessa** [comment]
There is one now. Any further discussion should be made in https://github.com/FOSSBilling/Proxmox. Thanks.
