### ISSUE TITLE
[Feature Request] FOSSBilling be conscious of server load when activating a customer order (ie. load balancing)

### ISSUE THREAD

**Issue by Coo-ops** [FOSSBilling/FOSSBilling#34]
https://github.com/boxbilling/boxbilling/issues/1284

What is the idea?

Instead of configuring a product to a specific server, you can leave it at random or go to a server with fewer customers

Such a function already exists in other panels
Why would this be beneficial

Avoiding the Creation of Several Equal Products for Different Servers and Avoiding Rewor

**Comment by John-S4** [comment]
> Such a function already exists in other panels

I'm not sure which other panels have this currently, if anyone knows I'm curious to check it out. 

I'm assuming that whoever wrote the post originally was referring to hosting control panels that support multiple servers, like ISPConfig (though I don't know if that supports this feature), but in that case really it's a task for the control panel rather than the billing solution.

**Comment by John-S4** [comment]
Closing this as nobody has provided a compelling reason why this is something that a billing panel should be aware of rather than being the remit of the hosting control panel.
