### ISSUE TITLE
[Feature Request] Helper tool to automatically migrate theme files

### ISSUE THREAD

**Issue by evrifaessa** [FOSSBilling/FOSSBilling#366]
A helper tool that automatically migrates theme files from BoxBilling.

- It should rename the files from .phtml to .html.twig
- It should adjust tags like "trans" to work with Twig 3.x.

**Comment by evrifaessa** [comment]
I have two different ways in my mind:

1. Make it a website, the user uploads a ZIP and downloads the migrated ZIP
1. a. Process the ZIP in the user's browser, use the user's device to do the tweaks
1. b. Process the ZIP on a server. Would we also need to write a privacy policy as we handle and process data even though we will delete it right after the process is done?

2. Make it a command-line app.

**Comment by jaapmarcus** [comment]
Do we really want to create a specific tool for a small number of users that can be trashed after we have released the Lara branch?

**Comment by evrifaessa** [comment]
> Do we really want to create a specific tool for a small number of users that can be trashed after we have released the Lara branch?

Yes, I think I should decide what I want to do in my spare time. It isn't a big project either.

**Comment by admdly** [comment]
Looking at this now - do we really want to focus energy on this?

**Comment by BelleNottelling** [comment]
I don't see this as being especially helpful. We've changed considerably more than we did back when this issue was created. It's no longer as simple as just renaming the files and fixing the trans tag. 

Plus, most themes for BoxBilling are already going to be quiet dated. I think efforts would be better directed at documentation for creating themes and eventually replacing Huraga
