### ISSUE TITLE
Decide on which adapters to keep

### ISSUE THREAD

**Issue by evrifaessa** [FOSSBilling/FOSSBilling#471]
As of right now, we have these payment/server/registrar adapters available in the core repository.

We should decide on which ones to keep, and drop the others until a community-maintained adapter appears.

### Payment adapters
- AliPay
- Interkassa
- Onebip
- PayPalEmail
- Stripe
- TwoCheckout
- WebMoney

### Domain registrars
- Internetbs
- NetEarth One
- Resell.biz
- ResellerClub
- ResellerID
- SRS-X

### Server managers
- CentOS Web Panel/Control Web Panel
- DirectAdmin
- Hestia
- ISPConfig
- Plesk
- Vesta
- Virtualmin
- WHM/cPanel
- Proxmox
- SolusVM

### Radio
- Centova Cast

**Comment by evrifaessa** [comment]
I think we should keep these. I left the others out either because I don't know them, I'm unsure or I think they should be maintained by the community:

### Payment adapters
- Stripe (needs some changes before upgrading to the next 3 major library releases)
- PayPal (should see if it even works)

### Registrars
I don't know much about any of them.

### Server managers
#### Definitely keep
- cPanel/WHM
- Plesk
- Hestia/Vesta
- Proxmox (has great demand)

#### Might be useful to keep
- DirectAdmin

I'm unsure about the others server managers.

**Comment by BelleNottelling** [comment]
We should be able to keep the CWP model, I created that a bit over a year ago so it should still work

**Comment by jaapmarcus** [comment]
If they work we should keep them if not remove them...

**Comment by cosmii02** [comment]
Paypal works fine

**Comment by notbasetwo** [comment]
The registrar modules need some work but are generally quite important registrars. I would consider moving Payment Processors that aren't Stripe/PayPal out of the core repository. 

Onebip can probably be shafted altogether, it doesn't really offer the same features it did many many years ago.

**Comment by xinomilo** [comment]
in favor of keeping Virtualmin, other people in Virtualmin forum have reported using BoxBilling/FOSSBilling. so, feeling it's of some use/demand tbh. 
i would maintain Virtualmin adapter myself, but i'm not a dev. ( btw, virtualmin adapter doesn't work.. another issue..)

**Comment by BelleNottelling** [comment]
Here's what I feel should be in the main repo:
## Payment Adapters
 - PayPal
 - Stripe (once fixed and properly working)

## Domain Registrars 
 - Basically anything that works

## Server Managers
 - CWP
 - HestiaCP 
 - cPanel
 - Plesk
 - Proxmox (as a seperate module ofc)

The rest of the adapters that exist are either broken or seemingly not popular.
And while it is extremely similar to the HestiaCP adapter, I honestly vote we completely remove the VestaCP adapter. VestaCP is abandoned and insecure so we shouldn't have a sever adapter for it to begin with imo

**Comment by heberq1978** [comment]
### Domain Registrars
Maintain the domain registration by email, because here in Brazil, we have to pay a lot to have access to the domain resale system. The email reseller system is helping me a lot.

**Comment by jaapmarcus** [comment]
> ### Domain Registrars
> Maintain the domain registration by email, because here in Brazil, we have to pay a lot to have access to the domain resale system. The email reseller system is helping me a lot.

The domain registration doesn't need any upkeep so it will remain available as it will just send an email to the admin user. 

Only change we need to make is replacing the broken whois system....

**Comment by coldwhiz** [comment]
It would be better to keep one in each, fix all the bugs in them, then use that one to expand later. 

**Payment adapters**
Paypal

**Domain registrars**
ANY One - The easiest one to signup and debug

**Server managers**
ANY One - The easiest one to signup and debug

**Comment by BelleNottelling** [comment]
> It would be better to keep one in each, fix all the bugs in them, then use that one to expand later.
> 
> **Payment adapters** Paypal
> 
> **Domain registrars** ANY One - The easiest one to signup and debug
> 
> **Server managers** ANY One - The easiest one to signup and debug

Definitely not.

In terms of payment gateways, we have Stripe and PayPal included which are both known working and we have an extension available for Mollie which is also known to be working without issue.

For server managers, CWP, HestiaCP, Direct Admin, and cPanel all work correctly. (Plesk as well, but I'm unsure if this has been tested recently)

If we kept only one payment gateway, that'd be 1/3rd of the currently working options. Doing the same for server managers would leave us with only 1/5th of the working options.

For registrar integrations, the Namecheap integration works just fine and the only other one that needs to be maintained (and fixed) is for Resellersclub. 

This issue is old and the list in it is inaccurate.

# Updated list

## Payment Gateways

Working: 
 - PayPal (working)
 - Stripe (working)
 - Mollie (Available as an extension, this one is also working)
 
 Unknown (Getting community info to decide if we should remove): 
 - AliPay
 - Interkassa
 - Onebip
 - TwoCheckout
 - WebMoney
 
 ## Server Managers
Working:
 - HestiaCP
 - CWP
 - WHM / cPanel
 - Direct Admin
 - Plesk

Not working:
 - ISPConfig 3
 - Virtualmin

## Domain Registrars
Working:
 - Namecheap

Not working:
 - Resellers club (This did work until fairly recently, possibly a regression due to changes made)

**Comment by John-S4** [comment]
To clarify the following payment gateways should be removed for the 0.6 release

- AliPay
- Interkassa
- Onebip
- WebMoney

TwoCheckout may be working but should be tested and moved to the Extension Directory if it is, as it will not be core maintained.

Unless someone knows better about server managers, then ISPConfig and Virtualmin are not working and should be removed. If they actually are functional then they should probably also be moved to the Extension Directory and can be community maintained.

**Comment by BelleNottelling** [comment]
@John-S4 These are all already removed and placed in their own separate repositories and a FOSSBilling user on our Discord stated that `TwoCheckout` is functional. 

The only things that haven't happened is a release with them removed & `TwoCheckout` isn't added to the Extension Directory yet

**Comment by John-S4** [comment]
@BelleNottelling Yep I noticed they were removed, the comment was more for public information since there was the question about it on Discord.
