### ISSUE TITLE
[Feature Request] MyOwnFreeHost/MOFH Support

### ISSUE THREAD

**Issue by chippytech** [FOSSBilling/FOSSBilling#506]
It would be nice to have MyOwnFreeHost support.
MyOwnFreeHost can get the username & can auto-login.
I am a MyOwnFreeHost reseller.
It even has support ticket support from iFastNet.

**Comment by BelleNottelling** [comment]
The one from BoxBilling should still work
https://github.com/boxbilling/extensions/blob/master/bb-library/Server/Manager/MOFH.php

**Comment by chippytech** [comment]
But that generates the username incorrectly & can't log in to the control panel.

**Comment by evrifaessa** [comment]
Definitely not.

We have tried that before. It's unnecessary work.

Speaking from personal experience: Due to MOFH's low entry threshold with absolutely no payment requirement, I can safely say the majority of the userbase don't know what they are doing and shouldn't be selling hosting in the first place.

This means unnecessary time spent by us to write the module and provide support for it.

I can't see any benefits to the project.

But yeah, there is an old adapter I wrote back in 2020, you can try that and see if you can go through the existing issues. We can put it to the extension store and everything. We just won't maintain it as the core team.

**Comment by jaapmarcus** [comment]
I don't think you want to resell "Free" web hosting from paying clients. If you already can't afford 10 / euro month on a reseller account why the * are doing in Web hosting... 

It is not worth our time to resolve the issues.
