### ISSUE TITLE
[Bug]I used the box API command set, but it is very difficult to use

### ISSUE THREAD

**Issue by github-oneyue** [FOSSBilling/FOSSBilling#507]
I checked the box's api and found that its design was very unreasonable. For example, each individual user has generated their own apikey, but it is impossible for me to go to the management background to view their apikey and then call it every time I create a user. This operation is really useless. I have the apikey of the super administrator. In theory, I can operate all the permissions of the user. For example, I can directly list the bill of the user, instead of using the current user's key to list the bill myself.

**Comment by evrifaessa** [comment]
If I got the question right, why do you need to access a customer’s API key?

API keys should be as private as user passwords, and you might be looking for the admin API instead of the client API.

If you elaborate the need further, I might be able to tell which admin API endpoint is the one you need.

**Comment by buycn** [comment]
Yes, what I need is permission to control some operations of each user, and output their information characteristics according to different users.

**Comment by admdly** [comment]
This issue appears to be outdated and unrelated to the current project. Please let us know if you are still having issues with the latest version of FOSSBilling.
