### ISSUE TITLE
[Feature Request] Require additional client information after account creation

### ISSUE THREAD

**Issue by tobsowo** [FOSSBilling/FOSSBilling#510]
The registration form for new client is good to quickly have the client start using the services but after making their first order can it be possible to get the client to be required as compulsory to submit all other required information like their name, phone, address, company, date of birth etc.

This is necessary for KYC and also to make sure when generating invoice the information there are not generic.

**Comment by BelleNottelling** [comment]
You can go into the client settings and select which fields are required during registration, use control on your keyboard to select multiple
![image](https://user-images.githubusercontent.com/17304943/206878412-3f8ac36d-4e9f-41ba-a698-ec853c14a42d.png)
Looks like this on the registration page:
![image](https://user-images.githubusercontent.com/17304943/206878397-9825fe7a-f159-4d40-bb2b-6f156fef4a4d.png)

**Comment by tobsowo** [comment]
Thanks Belle.

Just wondering where to quickly get someone onboard it is better to just ask a few information during registration so that they can pay for the service they need quickly but need them to update all other information later where forcing them to do that come in.

**Comment by BelleNottelling** [comment]
> Thanks Belle.
> 
> Just wondering where to quickly get someone onboard it is better to just ask a few information during registration so that they can pay for the service they need quickly but need them to update all other information later where forcing them to do that come in.

So you specifically want them to login, place an order, and then require them to enter their info?

**Comment by BelleNottelling** [comment]
Reopened and updated the title since the proposed solution doesn't match the original request / needs

**Comment by Anuril** [comment]
To be honest, this looks like a lot of work for a few specific edge cases. What is the reason for this request (What problem does it really solve?)

If the client needs an account to see pricing, they probably are not going to make an account anyway, no matter if you request only a few informations about them. 

If they register because they want to be your customer, you need the information again, and I think asking twice about personal information leads more to the question "Why didn't it ask me that when I had to enter my Name?" 

If you are required to comply with KYC Laws, you probably can't legally request payment from them and activate services for them before you got the information. 

Also, because the invoice creation process is closely linked with the order, the information needs to be in the system _before_ that happens, and adding that would require a rewrite of many many lines of code.

Imho this issue should be closed. What do you guys think @BelleNottelling, @John-S4 ?

**Comment by BelleNottelling** [comment]
@Anuril 

Honestly I never thought this one made any sense and kept meaning to come back, try to gather if there was any legal reasoning behind it, and then close it if not

**Comment by John-S4** [comment]
> Imho this issue should be closed. What do you guys think @BelleNottelling, @John-S4 ?

Sorry, completely missed this ping. 

This doesn't make any sense to me either. If someone is allowed to place an order before providing all of the requested info then it is no use for KYC/compliance, it is too late. 

So, yep, closing this again.

**Comment by tobsowo** [comment]
@John-S4 how does it feel like asking for address before making a purchase as such information may not want to be granted? Just yesterday, a client can't successfully but a domain linked to Namecheap because there was no address, although it was successful on FOSSBiling nothing gets recorded with Namecheap until the order was placed again after adding address.
