### ISSUE TITLE
[Bug] PayPal not backlinking

### ISSUE THREAD

**Issue by 0x6b-dev** [FOSSBilling/FOSSBilling#58]
https://github.com/boxbilling/boxbilling/issues/1059

**Comment by John-S4** [comment]
> PayPal IPN linking works. I'm working with @xSido at the moment to identify any other issues.
In this particular case, the problem was caused by csrfp which is included in master to mitigate a potential security vulnerability.

>But, this integration still leaves a few holes and causes problems like this. Because of that I have not included it in any release and I intend to come up with a different solution.
If you use one of the latest [releases](https://github.com/boxbilling/boxbilling/releases), you will NOT have that issue.

>That doesn't mean the PayPal integration is working 100%, but I hope xSido and I can find the cause easily

@BelleNottelling  Did you manage to identify the cause of this issue at all?

**Comment by BelleNottelling** [comment]
I absolutely forgot to respond to this. IIRC we never found an actual issue. I was about to use PayPal's developer tools to test it and it seemed like it worked fine. Documentation seemed to match what the integration was doing, and after a re-install I think it was working for Sido

**Comment by John-S4** [comment]
Closing this issue for now, as I have also just tested it and it does seem to be working.
