### ISSUE TITLE
[Feature Request] Custom Gateway

### ISSUE THREAD

**Issue by heberq1978** [FOSSBilling/FOSSBilling#694]
I would like some help, in the customized payment, which are the variables that can be used, because since Boxbilling, there is no place where there is a list of variables that can be used.

Thank You
Heber Queiroz - BR

**Comment by BelleNottelling** [comment]
There are no variables, it's used so you can display custom text to the client when they place an order, what use-case would variables have with it?

**Comment by heberq1978** [comment]
As html and css are accepted, there are payment systems that still work with forms, where we could be using variables for autocompletion, such as:
id, value, product name, product description, expiration date, among others that could be placed.

**Comment by BelleNottelling** [comment]
I'd like to have someone else on the team chime in their opinion on this, but imo if the intention is to use this as a way to create a new payment adapter, it would be a much better approach to actually create a custom payment adapter rather than trying to extend this to add support - primarily for security reasons, but also because basically any change to the custom adapter's code could break a hacked-together payment solution using it.

Actually going to ping @John-S4 for his opinion on this one

**Comment by jaapmarcus** [comment]
I agree with @BelleNottelling  it doesn't make sense to have it...

**Comment by John-S4** [comment]
> I'd like to have someone else on the team chime in their opinion on this, but imo if the intention is to use this as a way to create a new payment adapter, it would be a much better approach to actually create a custom payment adapter rather than trying to extend this to add support

I agree with this, it's not the best way to do it at all, and it would be much better to create a custom gateway, for both of the reasons that @BelleNottelling stated. 

**BUT** I think that what @heberq1978 is talking about was probably in line with the original intentions when this was written, because otherwise what possible reasons would there be for JS to be allowed and for their to be a callback URL.

**Comment by BelleNottelling** [comment]
Okay.. 1 year later, having been reminded about this, and knowing a bit more than I once did, I can say this is already as completed as it will be.
The HTML you configure is parsed through twig before getting sent to the browser and twig is also passed a few [variables](https://github.com/FOSSBilling/FOSSBilling/blob/main/src/library/Payment/Adapter/Custom.php#L62-L65) in the process. 

Enable debug mode for twig and then place this into your code: 
```TWIG
<pre>
    {{ dump(invoice) }}
</pre>
```
This will print out a representation of the invoice array that's being passed to twig and you'll be able to see all of the keys in it as well as their values.

What isn't possible is to actually handle a payment via this method which seems to be the original ask, but that was clearly never the intention of this payment gateway because it gives no way to setup a custom payment validation step, which would need to be handled via PHP code anyways so some custom HTML / JS just won't do it.

To the very best of my knowledge, the only purpose of the custom gateway is to give instructions to clients and manually handle the payment yourself and if you want to do more than that, then you need to just write a payment gateway integration.

I'll get a note up on the docs about the variables for this gateway in a bit in case anyone else has a similar question in the future, but I think that's the most we will do on that front.
