### ISSUE TITLE
[Bug] after update to 0.2.9 UNABLE to LOGIN [but able to register]

### ISSUE THREAD

**Issue by DineshKandasamy2k21** [FOSSBilling/FOSSBilling#735]
**Describe the bug**
After the update to 0.2.9 from 0.2.7 
There is no way to login back to either client panel or admin panel.
Cleared cache, cookies too. ( php.in values are corrected too )
Able to register new account and use it as long as the logout is not clicked, once logout thats it unable to login back again to the client panel
Admin panel is not even able to get a message for login or login error.

Just it was good working with 0.2.7.

**To Reproduce**
1. Go to 'Mayoza Billing](https://billing.mayoza.com) ' 
2. Click on 'register & logout once registered'
3. Click on 'login'

**Expected behavior**
Expected to login

**Screenshots**
no screenshots necessary, one can just register here and try to logout and login from the above url given

**Desktop (please complete the following information):**
 - OS: [Android]
 - Browser [Chrome]
 - Version [103]

**Smartphone (please complete the following information):**
 - Device: [Redmi 9A]
 - OS: [Android]
 - Browser [Chrome]
 - Version [103]

**Additional context**
Just make sure everything works as intended to work for everyone before releasing an update.

**Comment by DineshKandasamy2k21** [comment]
USE this test account to test login page!

USERNAME : test@test.com
PASSWORD : Test1234

**Comment by BelleNottelling** [comment]
It work perfectly fine for me. Logged out and back in multiple times. 
You are almost certainly having an issue with cache & haven't properly cleared it

**Comment by DineshKandasamy2k21** [comment]
No!
I am sure I am not having issues with cache
Since, I have cleared the cache locally and also the android device cache has been cleared
Also I tried fresh Browsers on android that I have never used for this login page.

Now you should try login from your mobile device!
Only then you may come to a conclusion.

I am having this particular problem with Fossbilling right from the update 0.2.9
Until I updated it, there were no problem in login and cache (if there is) whatsoever!

My question is
Why just logging in has been made so difficult? and cumbersome ?
If you say cache is the problem, then how come I am able to login gmail, HestaCP and many more websites without a problem?

There seems to be problem with Fossbilling itself!
Code from 0.2.9 is bugging for Mobile Devices I think.

Now I have the Bad Gateway error again.
I have corrected PHP.ini Apache2.conf and NGINX.conf
But now again I am running into the same gateway timeout error, now its error 502 & 504 combined.

There is a problem with the code.
![IMG_20230122_073752](https://user-images.githubusercontent.com/122649062/213897608-58f0540c-38a8-419c-935b-bc772f8b503e.jpg)

**Comment by DineshKandasamy2k21** [comment]
Other websites on the HestiaCP is running fine with no error on gateway!

**Comment by BelleNottelling** [comment]
> If you say cache is the problem, then how come I am able to login gmail, HestaCP and many more websites without a problem?

Cache is a per site thing. 



> Now I have the Bad Gateway error again.
> I have corrected PHP.ini Apache2.conf and NGINX.conf
> But now again I am running into the same gateway timeout error, now its error 502 & 504 combined.

Then you broke it.

**Comment by DineshKandasamy2k21** [comment]
No, you are not addressing the issue,

I can not "broke" something that is already broken.

You have not tested the website in mobile device, so I refrain your answers.

**Comment by BelleNottelling** [comment]
Okay :)

**Comment by DineshKandasamy2k21** [comment]
> Cache is a per site thing.

What a joke, that "per site" is fossbilling coded.

**Comment by heberq1978** [comment]
Friend, I understand your side, but ignorance will not help you at all.
Next, give more technical details, I am also using Fossbilling normally.
Another thing, it's in beta, so you also have to understand.
Pass the following data to be able to help you:
PHP version:
Apache:
NGINX:
MySQL version:
Active extensions in PHP:
One more thing, HestiaCP is totally Wordpress oriented, I tried to put other php systems on the server with HestiaCP and it didn't run like VestaCP normally runs.
I don't know if it's a bug in the panel itself or something else, nowadays I'm using aaPanel, everything runs without giving any errors. Think about it!

**Comment by John-S4** [comment]
> USE this test account to test login page!
> 
> USERNAME : [test@test.com](mailto:test@test.com) PASSWORD : Test1234

Works perfectly for me

**Comment by evrifaessa** [comment]
> USE this test account to test login page!
> 
> USERNAME : [test@test.com](mailto:test@test.com) PASSWORD : Test1234

Just tested both from my computer (Firefox 109 on Fedora Linux) and phone (Safari on iOS), it seems to work fine.

**Comment by DineshKandasamy2k21** [comment]
Ignorance is a strong word!

I am asking you the same question, let me know

You are ignorant in finding my issue stated up there.

And asking me to be not ignorant?

I am lightened, I have been working to solve this issue 12 hours straight!

I cant stand someone questioning my integrity to my work.

Listen up fellas, at the time of writing this message, the issue is somehow
vanished away in thin air!

I am a hosting provider starting to use Fossbilling for my commercial web
hosting company that provides the most affordable hosting plans to
consumers and for that I am working nights, nights and suddenly this error
comes with a 502 gateway error and login barring error.

And it disappears again! ( I am telling you it just disappears)

I can stand this error and move on, but I cant tell my customers if they
face the same issue to work around it or move on.

That is why I am keep pushing forward to the github issues page. Understand
it first.

I can go to paid billing solutions immediately! no burden for me!

But I wish to use opensource and give the customers no cost burden.

Coming Back to the Issue!

I was working on the LOGO Change! last day!

After I updated the billing panel using auto update, I tried to login back
after a voluntary logout!

I was unable to login from then till now,

I really think there is something sneaky going on inside the codes that
gives this error then and there (or) there is a timing set to auto purge
caches and cookies inside the code or a cron job that fixed the issue for
now.

I am sure, It started to happen only from the update!

There is something to update code!

Now, it is working normal, but I am wondering why It was not working for
the past 18 hours or so.

Think about it!

Without an issue I don't raise a ticket!

**Comment by evrifaessa** [comment]
We're glad you got it resolved. Have a nice day.

**Comment by DineshKandasamy2k21** [comment]
And mind your mouth before using the word ignorance, you and that kid are too quick and judgemental! watch it out!

**Comment by evrifaessa** [comment]
Alright. I'm locking this thread. Check our [code of conduct](https://fossbilling.org/docs/contribution-handbook/code-of-conduct) and have a nice day.

**Comment by jaapmarcus** [comment]
First of all as a Mainainer of Both HestiaCP and FOSSBilling. They are both open source and we provide it for free as is. We don't give any warranty at the moment and we will ever do in the future... And we try to debug as much as we can...  How ever bugs might slip trough.  

And with Fossbilling it is even in a state where we suggest to not use it ... 

If you don't like that please consider other software. 

With the release of 0.2.5 we have released a "feature" that would allow use to move away from jQuery dependency more and  add other additional features where some modules had issues with due to missing CSRF tokens. 

How ever this had some unexpected problems that were not intentional. And we had to patch out of it. Most issues were fixed in earlier version but some are still present in 0.2.7 and 0.2.8 and even 0.2.9. 

If you except everything to be working please go with WHMCS, Blesta or Hostbilling  as they allready offer a product that is production ready. If you want to go to an unstable pre release because it is free and expect  it to be working as WHMCS go away then.

Both the issues you tried to explain are mainly caused by the fact:
- Hestia has some timeouts build in that prevent the server to crash to easy. To prevent that execute long taks via cli or a cronjob. 
- Caching in Hestia is by default a bit to long espeacly if you javascript files are changing.

With the gateway time out you should check your server logs /var/log/apache2/domains/domain.com.error.log and see what the issue is. 

But if standard things like this are to difficult Hestia is not the product for you and we don't want you as a "client" of us. 

If you need support it is available for 100 euro / hr.  Or go with alternatives on Fiver / what ever. 

Support takes a lot of my time that I also can spend on development that I really like. If you expect more support check this and this and need us to check to login on your server except to pay for it. 

With HestiaCP we have +36k servers running. I can't debug every issue for free till the same level the most users except. I don't make any money out of this and if the software is used commercially why do users except me to work for free and solve there problems.  

Hestia should work fine with other php scripts and there should be no reason why it should't be working...
