### ISSUE TITLE
Weird stylesheet cdn

### ISSUE THREAD

**Issue by mirkobrombin** [FOSSBilling/FOSSBilling#759]
While looking at the [demo's source code](https://demo.fossbilling.org/themes/huraga/assets/css/huraga-main.css), I found the stylesheet is loaded via walkingpixels[dot]com which is... is.

May I ask why?
Is this intentional in some way?

**Comment by mirkobrombin** [comment]
It actually makes sense.

I was seeing if he was using Bootstrap as I am considering using FOSSBilling. I saw that and I thought it was right to let you know.

**Comment by BelleNottelling** [comment]
That's nothing more than the original developer for the Huraga theme, the CSS is loaded off whatever server is running FOSSBilling.

**Comment by mirkobrombin** [comment]
I appreciate your fast response. However, I must emphasize the seriousness of this issue. As you have mentioned, the CSS is loaded off whatever server is running FOSSBilling, which means that all websites using FOSSBilling will have a reference to a pornographic site in their source. This is not only unethical but also a potential security and reputation risk for the end users.

I would like to suggest that the issue be re-opened and addressed promptly. A simple solution could be to remove the CSS file from the source code or provide a warning to the users to remove it themselves. This way, the credibility and reputation of FOSSBilling and its users will be protected.

Thank you for your time and understanding. I look forward to your response.

**Comment by BelleNottelling** [comment]
The theme is from 2012, so someone else must have bought the domain. I'll submit a PR today to have that link changed to an archive.org listing of the original site before it went down. 

In the future, please be explicit in what is actually the issue, I don't think any of us looked at the site (never had a reason to). And you never actually started there was a content issue on it

**Comment by mirkobrombin** [comment]
> The theme is from 2012, so someone else must have bought the domain. I'll submit a PR today to have that link changed to an archive.org listing of the original site before it went down.
> 
> In the future, please be explicit in what is actually the issue, I don't think any of us looked at the site (never had a reason to). And you never actually stated there was a content issue on it

I admit that the text of the issue may not have been too clear, my intention was to avoid making the content of the link known as this conversation is public and not filtered to minors.

I hope I don't sound rude but I invite you to check the links that are reported for the future. If it is normal for an expired domain to be bought by malicious people, it is equally normal to open a link that is reported, since this is present in the source code of the project and it is part of your responsibility.

Best regards.

**Comment by evrifaessa** [comment]
> I found the stylesheet is loaded via...

While the issue is legitmate, I want to clear some confusion here. 

It's just a link inside a comment and not an actual import or anything. No code is pulled from that website, no requests are made to it.

Nothing is "loaded via" it. The stylesheet is hosted locally. We are doing our best to keep it that way and minimize the project's dependency on external hosts.

Regardless, in my opinion the link there can be converted to a simple text reference to "Walking Pixels" or just removed.

I'm a little unsure because Huraga is likely older than a decade and we have no way to validate how the original author or license would want us to attribute their work.

> I hope I don't sound rude but I invite you to check the links that are reported for the future. If it is normal for an expired domain to be bought by malicious people, it is equally normal to open a link that is reported, since this is present in the source code of the project and it is part of your responsibility.

I honestly respect the issue and appreciate the report. Thanks for bringing it up. It should be handled by a pull request soon.

**Comment by John-S4** [comment]
I think there are a couple of things that need to be taken into account here. 

The first one is that nothing is actually loaded from the site in question, it's not loading a stylesheet from anywhere. 

The second is that the link in question exists as attribution to the original theme authors, and so in normal circumstances it should not be removed or changed. Attribution remains even if the original authors are no longer actively updating something. 

The final one is that while in an ideal world somebody probably should have noticed it by now, it really isn't the responsibility of any one project to check whether the sites that are in an attribution notice change over time. That said, we should have picked up on it and will try to do better in the future. 

In this case the link will be removed from the stylesheet shortly, since it is clearly not serving any purpose for attribution anymore. 

We are working hard to improve FOSSBilling from the inherited quite ancient code that contained lots of issues, we are getting there bit by bit, let's all work together to keep moving forward.

**Comment by John-S4** [comment]
Apologies for the double post saying very similar things, @evrifaessa and I were obviously typing at the same time with similar thoughts.

**Comment by mirkobrombin** [comment]
Thank you for understanding and I apologize if my initial comment may seem superficial. Keep up the good work!

**Comment by evrifaessa** [comment]
Thanks! Wishing you a great evening and good luck on Bottles :-) It's a great app and I've been using it for quite some time now.

**Comment by BelleNottelling** [comment]
@mirkobrombin Thank you for bringing it to our attention, even if it took a moment for us to all get on the same page. If you do find any other issue, please feel free to open new issues on our GitHub.

The PR is live, I've opted to remove the link entirely. See https://github.com/FOSSBilling/FOSSBilling/pull/760

Additionally, if you use Discord, we have one here https://fossbilling.org/discord and I know that I personally would be happy to receive content reports like this via a DM when you are concerned about it's visibility by minors. 

Take care! 😄

**Comment by John-S4** [comment]
PR Merged
