### ISSUE TITLE
[Feature Request] Enhance panel integration

### ISSUE THREAD

**Issue by J0shh** [FOSSBilling/FOSSBilling#776]
Enhance is a new and upcoming website panel and am hoping for it to be supported inside FOSSBilling and I'm sure the community would also feel the same way. It also has an extensive API allowing full functionality within FOSSBilling easier 

https://apidocs.enhance.com/

**Comment by John-S4** [comment]
Closing this and rolling all control panel integration requests into one larger issue #1362

**Comment by admdly** [comment]
> Up to Enhance control panel! 

 _Originally posted by @alexandreangelis in [#1362](https://github.com/FOSSBilling/FOSSBilling/issues/1362#issuecomment-1604527258)_
👍+11

**Comment by kairandles** [comment]
Hey, I've built an Enhance integration for myself, fully tested against my instance with adopting existing customers & their plan(s), as well as commissioning new ones, or adding plans to existing customers accounts etc. Also tested Single Sign on from the customer service page, and the usual, suspend, unsuspend & cancel.
Just wondering if I was to publish it, would you prefer it as an extension or a PR to the main repo? - I know the docs mention you're not really focusing on it right now

Separately, I have a small core change that calls synchronizeAccount() right after activation so a manager can report the real username and IP back to FOSSBilling. For Enhance that means customers see their actual login (their email) instead of a generated username. It doesn't appear to have any consequence for the existing managers too. Happy to open that as its own PR regardless of the answer above.

**Comment by jaapmarcus** [comment]
> Hey [@admdly](https://github.com/admdly), I've built an Enhance integration for myself, fully tested against my instance with adopting existing customers & their plan(s), as well as commissioning new ones, or adding plans to existing customers accounts etc. Also tested Single Sign on from the customer service page, and the usual, suspend, unsuspend & cancel. Just wondering if I was to publish it, would you prefer it as an extension or a PR to the main repo? - I know the docs mention you're not really focusing on it right now

Please create a new extension. 

> Separately, I have a small core change that calls synchronizeAccount() right after activation so a manager can report the real username and IP back to FOSSBilling. For Enhance that means customers see their actual login (their email) instead of a generated username. It doesn't appear to have any consequence for the existing managers too. Happy to open that as its own PR regardless of the answer above.

Go a head and create a PR :)

**Comment by kairandles** [comment]
This is now live on https://extensions.fossbilling.org/extension/enhance if anyone on this thread wants it, please do raise any issues on the repo & I'll take a look :)

**Comment by admdly** [comment]
> Hey, I've built an Enhance integration for myself, fully tested against my instance with adopting existing customers & their plan(s), as well as commissioning new ones, or adding plans to existing customers accounts etc. Also tested Single Sign on from the customer service page, and the usual, suspend, unsuspend & cancel. Just wondering if I was to publish it, would you prefer it as an extension or a PR to the main repo? - I know the docs mention you're not really focusing on it right now

I've gone ahead and approved this - thank you again for submitting an extension and contributing to FOSSBilling. 🙂 We can add this to 'docs' and close this issue with a link to the extension if you plan to maintain it.

**Comment by kairandles** [comment]
Of course, and yes i'll be using it for myself so will keep it up to date with new versions & add features where i find them useful or people request
